name: Trigger auto deployment for github-runner-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/github-runner-app-AutoDeployTrigger-5c69876c-b11c-4263-84ca-ab3a6bb5dd57.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.GITHUBRUNNERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: rajnishacr001.azurecr.io
          registryUsername: ${{ secrets.GITHUBRUNNERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GITHUBRUNNERAPP_REGISTRY_PASSWORD }}
          containerAppName: github-runner-app
          resourceGroup: rg-github-runner
          imageToBuild: rajnishacr001.azurecr.io/github-runner-app:${{ github.sha }}
          
            

     

